<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Central Park Data Analysis</title>

<script src="site_libs/header-attrs-2.16/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://yc4195.shinyapps.io/DS_final_squirrel_tracker/">Squirrel Tracker APP</a>
</li>
<li>
  <a href="https://yc4195.shinyapps.io/location_predictor/">Location Predictor APP</a>
</li>
<li>
  <a href="P8105_final_proposal.html">Proposal</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Exploratory Analyses
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="model.html">Central Park Data Analysis</a>
    </li>
    <li>
      <a href="sqr_nyc.html">NYC Data Analysis</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Inferential Statistics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="function.html">Predictive Model Building</a>
    </li>
    <li>
      <a href="stat-test.html">Statistics Testing</a>
    </li>
  </ul>
</li>
<li>
  <a href="report-writing.html">Report</a>
</li>
<li>
  <a href="https://github.com/yiminchen1999/DS_final.github.io">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Central Park Data Analysis</h1>

</div>


<div id="model-building" class="section level1">
<h1>Model Building</h1>
<p>This will be model building procedure…</p>
<pre class="r"><code>sq_df = read_csv(&#39;squirrel_tidy.csv&#39;) %&gt;% 
  janitor::clean_names()</code></pre>
<div id="p-value" class="section level2">
<h2>P-value</h2>
<p>The first step is to throw all the numerical variables into the model
and check the p-value, the variables are shift + age + primary_fur_color
+ location + activity + reaction + sounds. Although hectare is also a
numerical variable, it’s not included because the users of the model
would not have the information of how many squirrels are there within a
specific hectare, but they only have the information about the
characteristics of specific squirrels that they want to look for. The
variables with p-value less than 0.05 were removed from the model, and
the model built with remaining variables was checked again to make sure
that all of them had p-value less than 0.05. So, the first model
candidate was produced with predictors being ‘shift’, ’ age’,
‘activity’, ‘reaction’, ‘sounds’.</p>
<pre class="r"><code># longitudinal/latitudinal function
# raw data input (no hectare information because the user would not know the info. about it)
long_model =
  lm(long ~ shift + age + primary_fur_color + location + activity + reaction + sounds, data = sq_df)
summary(long_model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = long ~ shift + age + primary_fur_color + location + 
##     activity + reaction + sounds, data = sq_df)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.015965 -0.005875 -0.001331  0.006604  0.019146 
## 
## Coefficients:
##                     Estimate Std. Error    t value Pr(&gt;|t|)    
## (Intercept)       -7.397e+01  8.390e-04 -88161.363  &lt; 2e-16 ***
## shift              5.763e-04  2.831e-04      2.036  0.04187 *  
## age               -9.137e-04  3.676e-04     -2.486  0.01299 *  
## primary_fur_color -5.253e-04  2.797e-04     -1.878  0.06053 .  
## location           1.836e-04  3.008e-04      0.610  0.54165    
## activity          -2.371e-04  1.054e-04     -2.250  0.02454 *  
## reaction           5.130e-04  1.691e-04      3.034  0.00243 ** 
## sounds             2.081e-03  4.895e-04      4.251 2.19e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.007675 on 3015 degrees of freedom
## Multiple R-squared:  0.01547,    Adjusted R-squared:  0.01319 
## F-statistic: 6.768 on 7 and 3015 DF,  p-value: 5.462e-08</code></pre>
<pre class="r"><code>print(long_model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = long ~ shift + age + primary_fur_color + location + 
##     activity + reaction + sounds, data = sq_df)
## 
## Coefficients:
##       (Intercept)              shift                age  primary_fur_color  
##        -7.397e+01          5.763e-04         -9.137e-04         -5.253e-04  
##          location           activity           reaction             sounds  
##         1.836e-04         -2.371e-04          5.130e-04          2.081e-03</code></pre>
<pre class="r"><code>lat_model =
  lm(lat ~ shift + age + primary_fur_color + location + activity + reaction + sounds, data = sq_df)
summary(lat_model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = lat ~ shift + age + primary_fur_color + location + 
##     activity + reaction + sounds, data = sq_df)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.019660 -0.008937 -0.002902  0.010291  0.021841 
## 
## Coefficients:
##                     Estimate Std. Error   t value Pr(&gt;|t|)    
## (Intercept)        4.078e+01  1.116e-03 36541.411  &lt; 2e-16 ***
## shift              6.023e-04  3.766e-04     1.599 0.109878    
## age               -7.666e-04  4.890e-04    -1.568 0.117052    
## primary_fur_color -1.260e-03  3.721e-04    -3.385 0.000721 ***
## location          -8.062e-05  4.001e-04    -0.201 0.840342    
## activity          -2.279e-04  1.402e-04    -1.626 0.104045    
## reaction           7.655e-04  2.249e-04     3.404 0.000673 ***
## sounds             2.934e-03  6.512e-04     4.505 6.88e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.01021 on 3015 degrees of freedom
## Multiple R-squared:  0.01692,    Adjusted R-squared:  0.01464 
## F-statistic: 7.413 on 7 and 3015 DF,  p-value: 7.361e-09</code></pre>
<pre class="r"><code>print(lat_model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = lat ~ shift + age + primary_fur_color + location + 
##     activity + reaction + sounds, data = sq_df)
## 
## Coefficients:
##       (Intercept)              shift                age  primary_fur_color  
##         4.078e+01          6.023e-04         -7.666e-04         -1.260e-03  
##          location           activity           reaction             sounds  
##        -8.062e-05         -2.279e-04          7.655e-04          2.934e-03</code></pre>
<pre class="r"><code># model selection using p-value
long_model1 = 
  lm(long ~ shift + age + activity + reaction + sounds, data = sq_df)
summary(long_model1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = long ~ shift + age + activity + reaction + sounds, 
##     data = sq_df)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.015899 -0.005878 -0.001336  0.006651  0.018671 
## 
## Coefficients:
##               Estimate Std. Error    t value Pr(&gt;|t|)    
## (Intercept) -7.397e+01  6.978e-04 -1.060e+05  &lt; 2e-16 ***
## shift        5.639e-04  2.817e-04  2.001e+00  0.04543 *  
## age         -9.412e-04  3.663e-04 -2.569e+00  0.01024 *  
## activity    -2.267e-04  1.031e-04 -2.200e+00  0.02787 *  
## reaction     4.809e-04  1.681e-04  2.862e+00  0.00424 ** 
## sounds       2.142e-03  4.873e-04  4.396e+00 1.14e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.007678 on 3017 degrees of freedom
## Multiple R-squared:  0.01419,    Adjusted R-squared:  0.01255 
## F-statistic: 8.684 on 5 and 3017 DF,  p-value: 3.478e-08</code></pre>
<pre class="r"><code>print(long_model1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = long ~ shift + age + activity + reaction + sounds, 
##     data = sq_df)
## 
## Coefficients:
## (Intercept)        shift          age     activity     reaction       sounds  
##  -7.397e+01    5.639e-04   -9.412e-04   -2.267e-04    4.809e-04    2.142e-03</code></pre>
<pre class="r"><code>lat_model1 =
  lm(lat ~ primary_fur_color + reaction + sounds, data = sq_df)
summary(lat_model1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = lat ~ primary_fur_color + reaction + sounds, data = sq_df)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.019726 -0.009004 -0.002850  0.010370  0.021857 
## 
## Coefficients:
##                     Estimate Std. Error   t value Pr(&gt;|t|)    
## (Intercept)       40.7814005  0.0005212 78244.152  &lt; 2e-16 ***
## primary_fur_color -0.0013140  0.0003716    -3.536 0.000412 ***
## reaction           0.0007784  0.0002234     3.484 0.000501 ***
## sounds             0.0029072  0.0006480     4.486 7.51e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.01022 on 3019 degrees of freedom
## Multiple R-squared:  0.01405,    Adjusted R-squared:  0.01307 
## F-statistic: 14.34 on 3 and 3019 DF,  p-value: 2.813e-09</code></pre>
<pre class="r"><code>print(lat_model1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = lat ~ primary_fur_color + reaction + sounds, data = sq_df)
## 
## Coefficients:
##       (Intercept)  primary_fur_color           reaction             sounds  
##        40.7814005         -0.0013140          0.0007784          0.0029072</code></pre>
</div>
<div id="automaticstepwise" class="section level2">
<h2>Automatic(Stepwise)</h2>
<p>Then, we selected model using automatic procedure, specifically
step-wise regression procedure. Backward, Forward or step-wise methods
might produce different results, but we chose to use step-wise since it
gives a single ‘best’ model. As the result, except for the location, all
other 6 variables are included in this model, which is the second model
candidate.</p>
<pre class="r"><code># model selection using automatic procedure (forward/backward)
model_stepwise_long &lt;- lm(long ~ shift + age + primary_fur_color + location + activity + reaction + sounds, data = sq_df)
ols_step_both_p(model_stepwise_long)</code></pre>
<pre><code>## 
##                                    Stepwise Selection Summary                                     
## -------------------------------------------------------------------------------------------------
##                               Added/                   Adj.                                          
## Step        Variable         Removed     R-Square    R-Square     C(p)          AIC         RMSE     
## -------------------------------------------------------------------------------------------------
##    1         sounds          addition       0.006       0.006    25.1010    -20836.6444    0.0077    
##    2        reaction         addition       0.009       0.008    18.6660    -20843.0326    0.0077    
##    3           age           addition       0.011       0.010    13.3070    -20848.3696    0.0077    
##    4        activity         addition       0.013       0.012     9.9410    -20851.7308    0.0077    
##    5          shift          addition       0.014       0.013     7.9330    -20853.7419    0.0077    
##    6    primary_fur_color    addition       0.015       0.013     6.3730    -20855.3088    0.0077    
## -------------------------------------------------------------------------------------------------</code></pre>
<pre class="r"><code>model_stepwise_lat &lt;- lm(lat ~ shift + age + primary_fur_color + location + activity + reaction + sounds, data = sq_df)
ols_step_both_p(model_stepwise_lat)</code></pre>
<pre><code>## 
##                                    Stepwise Selection Summary                                     
## -------------------------------------------------------------------------------------------------
##                               Added/                   Adj.                                          
## Step        Variable         Removed     R-Square    R-Square     C(p)          AIC         RMSE     
## -------------------------------------------------------------------------------------------------
##    1         sounds          addition       0.007       0.006    27.7780    -19108.7958    0.0103    
##    2    primary_fur_color    addition       0.010       0.009    18.9560    -19117.5522    0.0102    
##    3        reaction         addition       0.014       0.013     8.7970    -19127.6836    0.0102    
##    4        activity         addition       0.015       0.014     7.3460    -19129.1353    0.0102    
##    5          shift          addition       0.016       0.014     6.5490    -19129.9364    0.0102    
## -------------------------------------------------------------------------------------------------</code></pre>
</div>
<div id="criterion-based" class="section level2">
<h2>Criterion-based</h2>
<p>Next, we used criterion-based procedure. The model with the largest
adjusted R-square valued along with smallest AIC and BIC values are
chosen to be the model candidate. It turned out that it also had all
those 6 variables as the one in automatic procedure.</p>
<pre class="r"><code># model selection using criterion-based procedure
model_criterion_long = lm(long ~ shift + age + primary_fur_color + location + activity + reaction + sounds, data = sq_df)
ols_step_best_subset(model_criterion_long)</code></pre>
<pre><code>##                           Best Subsets Regression                           
## ----------------------------------------------------------------------------
## Model Index    Predictors
## ----------------------------------------------------------------------------
##      1         sounds                                                        
##      2         reaction sounds                                               
##      3         age reaction sounds                                           
##      4         age activity reaction sounds                                  
##      5         shift age activity reaction sounds                            
##      6         shift age primary_fur_color activity reaction sounds          
##      7         shift age primary_fur_color location activity reaction sounds 
## ----------------------------------------------------------------------------
## 
##                                                        Subsets Regression Summary                                                       
## ----------------------------------------------------------------------------------------------------------------------------------------
##                        Adj.        Pred                                                                                                  
## Model    R-Square    R-Square    R-Square     C(p)          AIC           SBIC            SBC         MSEP      FPE      HSP       APC  
## ----------------------------------------------------------------------------------------------------------------------------------------
##   1        0.0060      0.0056      0.0047    25.1007    -20836.6444    -29415.5745    -20818.6023    0.1794    1e-04    0.0000    0.9953 
##   2        0.0087      0.0081      0.0068    18.6656    -20843.0326    -29421.9600    -20818.9766    0.1790    1e-04    0.0000    0.9932 
##   3        0.0111      0.0101      0.0085    13.3068    -20848.3696    -29427.2860    -20818.2995    0.1786    1e-04    0.0000    0.9915 
##   4        0.0129      0.0116      0.0096     9.9410    -20851.7308    -29430.6329    -20815.6467    0.1784    1e-04    0.0000    0.9904 
##   5        0.0142      0.0126      0.0103     7.9325    -20853.7419    -29432.6281    -20811.6439    0.1782    1e-04    0.0000    0.9897 
##   6        0.0153      0.0134      0.0108     6.3726    -20855.3088    -29434.1758    -20807.1967    0.1780    1e-04    0.0000    0.9892 
##   7        0.0155      0.0132      0.0103     8.0000    -20853.6823    -29432.5423    -20799.5563    0.1781    1e-04    0.0000    0.9898 
## ----------------------------------------------------------------------------------------------------------------------------------------
## AIC: Akaike Information Criteria 
##  SBIC: Sawa&#39;s Bayesian Information Criteria 
##  SBC: Schwarz Bayesian Criteria 
##  MSEP: Estimated error of prediction, assuming multivariate normality 
##  FPE: Final Prediction Error 
##  HSP: Hocking&#39;s Sp 
##  APC: Amemiya Prediction Criteria</code></pre>
<pre class="r"><code>model_criterion_lat &lt;- lm(lat ~ shift + age + primary_fur_color + location + activity + reaction + sounds, data = sq_df)
ols_step_best_subset(model_criterion_lat)</code></pre>
<pre><code>##                           Best Subsets Regression                           
## ----------------------------------------------------------------------------
## Model Index    Predictors
## ----------------------------------------------------------------------------
##      1         sounds                                                        
##      2         primary_fur_color sounds                                      
##      3         primary_fur_color reaction sounds                             
##      4         primary_fur_color activity reaction sounds                    
##      5         shift primary_fur_color activity reaction sounds              
##      6         shift age primary_fur_color activity reaction sounds          
##      7         shift age primary_fur_color location activity reaction sounds 
## ----------------------------------------------------------------------------
## 
##                                                        Subsets Regression Summary                                                       
## ----------------------------------------------------------------------------------------------------------------------------------------
##                        Adj.        Pred                                                                                                  
## Model    R-Square    R-Square    R-Square     C(p)          AIC           SBIC            SBC         MSEP      FPE      HSP       APC  
## ----------------------------------------------------------------------------------------------------------------------------------------
##   1        0.0066      0.0062      0.0053    27.7776    -19108.7958    -27687.7295    -19090.7538    0.3178    1e-04    0.0000    0.9948 
##   2        0.0101      0.0094      0.0081    18.9558    -19117.5522    -27696.4802    -19093.4962    0.3168    1e-04    0.0000    0.9919 
##   3        0.0141      0.0131      0.0114     8.7968    -19127.6836    -27706.5881    -19097.6136    0.3156    1e-04    0.0000    0.9886 
##   4        0.0152      0.0139      0.0119     7.3462    -19129.1353    -27708.0289    -19093.0513    0.3154    1e-04    0.0000    0.9881 
##   5        0.0161      0.0145      0.0122     6.5488    -19129.9364    -27708.8171    -19087.8384    0.3152    1e-04    0.0000    0.9878 
##   6        0.0169      0.0149      0.0124     6.0406    -19130.4502    -27709.3157    -19082.3382    0.3150    1e-04    0.0000    0.9877 
##   7        0.0169      0.0146      0.0118     8.0000    -19128.4909    -27707.3509    -19074.3649    0.3151    1e-04    0.0000    0.9883 
## ----------------------------------------------------------------------------------------------------------------------------------------
## AIC: Akaike Information Criteria 
##  SBIC: Sawa&#39;s Bayesian Information Criteria 
##  SBC: Schwarz Bayesian Criteria 
##  MSEP: Estimated error of prediction, assuming multivariate normality 
##  FPE: Final Prediction Error 
##  HSP: Hocking&#39;s Sp 
##  APC: Amemiya Prediction Criteria</code></pre>
</div>
<div id="lasso" class="section level2">
<h2>LASSO</h2>
<p>LASSO model selection method was then used. After looking for the
best lamda value, the third model candidate has all seven predictors,
which means no variable was deleted from the selection procedure.</p>
<pre class="r"><code># model selection using LASSO procedure: longitude
y_long &lt;- sq_df$long
# hist(y_long)
x &lt;- sq_df %&gt;% 
  dplyr::select(
    shift, age, primary_fur_color,location, activity, reaction, sounds
    ) %&gt;%
  data.matrix()

set.seed(2022)
cv_model_long &lt;- cv.glmnet(x,y_long, alpha = 1)
best_lambda_long &lt;- cv_model_long$lambda.min
long_lasso &lt;- glmnet(x, y_long, alpha = 1, lambda = best_lambda_long)
coef(long_lasso)</code></pre>
<pre><code>## 8 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                              s0
## (Intercept)       -7.396680e+01
## shift              5.713470e-04
## age               -9.081172e-04
## primary_fur_color -5.210497e-04
## location           1.768355e-04
## activity          -2.351475e-04
## reaction           5.096738e-04
## sounds             2.073993e-03</code></pre>
<pre class="r"><code># model selection using LASSO procedure: latitude
y_lat &lt;- sq_df$lat
# hist(y_lat)
x &lt;- sq_df %&gt;% 
  dplyr::select(
    shift, age, primary_fur_color,location, activity, reaction, sounds
    ) %&gt;%
  data.matrix()

set.seed(2023)
cv_model_lat &lt;- cv.glmnet(x,y_lat, alpha = 1)
best_lambda_lat &lt;- cv_model_lat$lambda.min
lat_lasso &lt;- glmnet(x, y_lat, alpha = 1, lambda = best_lambda_lat)
coef(lat_lasso)</code></pre>
<pre><code>## 8 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                              s0
## (Intercept)       40.7816933208
## shift              0.0004907211
## age               -0.0006332138
## primary_fur_color -0.0011405094
## location           .           
## activity          -0.0001948355
## reaction           0.0006874044
## sounds             0.0027034309</code></pre>
</div>
</div>
<div id="model-selection" class="section level1">
<h1>Model Selection</h1>
<p>We have four different models as the final ‘best’ model candidate for
now, and they are all nested within each other. We choose the ‘best’
model according to 3 criteria, the adjusted R-squared value, the
cross-validation outcome(i.e. RMSE) and the rule of parsimony.</p>
<div id="prediction-models" class="section level2">
<h2>Prediction models</h2>
<p>The four different longitude-prediction model are as follows:</p>
<p>pvalue_fit_long = lm(long ~ shift + age + activity + reaction +
sounds, data = sq_df)</p>
<p>auto_fit_long = lm(long ~ shift + hectare_squirrel_number +
primary_fur_color + location + activity + reaction + sounds, data =
sq_df)</p>
<p>crit_fit_long &lt;- lm(long ~ hectare_squirrel_number +
primary_fur_color + location + activity + reaction + sounds, data =
sq_df)</p>
<p>lasso_fit_long = lm(long ~ shift + age + primary_fur_color + location
+ activity + reaction + sounds, data = sq_df)</p>
<pre class="r"><code># all longitudinal models
pvalue_fit_long = lm(long ~ shift + age + activity + reaction + sounds, data = sq_df)
pvalue_adjrsquared_long &lt;- summary(pvalue_fit_long)$adj.r.squared

auto_fit_long = lm(long ~ sounds + primary_fur_color + reaction + activity + shift ,data = sq_df)
auto_adjrsquared_long &lt;- summary(auto_fit_long)$adj.r.squared

crit_fit_long = lm(long ~ shift + age + primary_fur_color + activity + reaction + sounds, data = sq_df)
crit_adjrsquared_long &lt;- summary(crit_fit_long)$adj.r.squared

lasso_fit_long = lm(long ~ shift + age + primary_fur_color + location + activity + reaction + sounds, data = sq_df)
lasso_adjrsquared_long &lt;- summary(lasso_fit_long)$adj.r.squared</code></pre>
<p>The four different latitude-prediction model are as follows:</p>
<p>pvalue_fit_lat = lm(lat ~ primary_fur_color + reaction + sounds, data
= sq_df)</p>
<p>auto_fit_lat = lm(lat ~ sounds + primary_fur_color + reaction +
activity + shift ,data = sq_df)</p>
<p>crit_fit_lat = lm(lat ~ shift + age + primary_fur_color + activity +
reaction + sounds, data = sq_df)</p>
<p>lasso_fit_lat = lm(lat ~ shift + age + primary_fur_color + activity +
reaction + sounds, data = sq_df)</p>
<pre class="r"><code># all latitudinal models
pvalue_fit_lat = lm(lat ~ primary_fur_color + reaction + sounds, data = sq_df)
pvalue_adjrsquared_lat &lt;- summary(pvalue_fit_lat)$adj.r.squared

auto_fit_lat = lm(lat ~ sounds + primary_fur_color + reaction + activity + shift ,data = sq_df)
auto_adjrsquared_lat &lt;- summary(auto_fit_lat)$adj.r.squared

crit_fit_lat = lm(lat ~ shift + age + primary_fur_color + activity +  reaction + sounds, data = sq_df)
crit_adjrsquared_lat &lt;- summary(crit_fit_lat)$adj.r.squared

lasso_fit_lat = lm(lat ~ shift + age + primary_fur_color + activity + reaction + sounds, data = sq_df)
lasso_adjrsquared_lat &lt;- summary(lasso_fit_lat)$adj.r.squared</code></pre>
</div>
<div id="cross-validation" class="section level2">
<h2>Cross Validation</h2>
<p>The cross-validation divides model into the training set and the
testing set. Models’ comparison could be further done by comparing the
cross-validation output: RMSE.</p>
<pre class="r"><code># training and testing sets
cv_df &lt;- crossv_mc(sq_df, 100)
cv_df &lt;- cv_df %&gt;% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )</code></pre>
<pre class="r"><code># longitudinal model selection
cv_df_long = 
  cv_df %&gt;% 
  mutate(
    pvalue_fit = map(train, ~lm(long ~ shift + age + activity + reaction + sounds, data = .x)),
    auto_fit = map(train, ~lm(long ~ sounds + primary_fur_color + reaction + activity + shift ,data = .x)),
    crit_fit = map(train, ~lm(long ~ shift + age + primary_fur_color + activity + reaction + sounds, data = .x)),
    lasso_fit = map(train, ~lm(long ~ shift + age + primary_fur_color + location + activity + reaction + sounds, data = .x))
  ) %&gt;% 
  mutate(
    rmse_pvalue = map2_dbl(pvalue_fit, test, ~modelr::rmse(model = .x, data = .y)),
    rmse_auto = map2_dbl(auto_fit, test, ~modelr::rmse(model = .x, data = .y)),
    rmse_crit = map2_dbl(crit_fit, test, ~modelr::rmse(model = .x, data = .y)),
    rmse_lasso = map2_dbl(lasso_fit, test, ~modelr::rmse(model = .x, data = .y))
  )

# Comparing the RMSE plot

rplot_long &lt;- cv_df_long %&gt;% 
  dplyr::select(starts_with(&quot;rmse&quot;)) %&gt;% 
  pivot_longer(
    everything(),
    names_to = &quot;model&quot;, 
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_&quot;) %&gt;% 
  mutate(model = fct_inorder(model)) %&gt;% 
  ggplot(aes(x = model, y = rmse)) + geom_violin() +
  labs(
    title = &#39;RMSE for Cross Validation of Longitudinal Models&#39;,
       x = &#39;models&#39;, y = &#39;RMSE&#39;
  )+
  theme_bw()

# latitudinal model selection
cv_df_lat = 
  cv_df %&gt;% 
  mutate(
    pvalue_fit = map(train, ~lm(lat ~ primary_fur_color + reaction + sounds, data = .x)),
    auto_fit = map(train, ~lm(lat ~ sounds + primary_fur_color + reaction + activity + shift ,data = .x)),
    crit_fit = map(train, ~lm(lat ~ shift + age + primary_fur_color + activity +  reaction + sounds, data = .x)),
    lasso_fit = map(train, ~lm(lat ~ shift + age + primary_fur_color + activity + reaction + sounds, data = .x))
  ) %&gt;%
  mutate(
    rmse_pvalue = map2_dbl(pvalue_fit, test, ~modelr::rmse(model = .x, data = .y)),
    rmse_auto = map2_dbl(auto_fit, test, ~modelr::rmse(model = .x, data = .y)),
    rmse_crit = map2_dbl(crit_fit, test, ~modelr::rmse(model = .x, data = .y)),
    rmse_lasso = map2_dbl(lasso_fit, test, ~modelr::rmse(model = .x, data = .y))
  )

# Comparing the RMSE plot

rplot_lat &lt;- cv_df_lat %&gt;% 
  dplyr::select(starts_with(&quot;rmse&quot;)) %&gt;% 
  pivot_longer(
    everything(),
    names_to = &quot;model&quot;, 
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_&quot;) %&gt;% 
  mutate(model = fct_inorder(model)) %&gt;% 
  ggplot(aes(x = model, y = rmse)) + geom_violin() +
  labs(
    title = &#39;RMSE for Cross Validation of Latitudinal Models&#39;,
       x = &#39;models&#39;, y = &#39;RMSE&#39;
  )+
  theme_bw()

rplot_long + rplot_lat</code></pre>
<p><img src="function_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
<div id="visualization-tables" class="section level2">
<h2>Visualization Tables</h2>
<p>Visualization Tables are made for better comparison.</p>
<pre class="r"><code># RMSE and adj Rsquared comparison table
methods &lt;- c(&#39;pvalue&#39;,&#39;automatic&#39;,&#39;criterion-based&#39;,&#39;LASSO&#39;)
#longitude: parsimony since the RMSE and Rsquared are similar
RMSE_long &lt;- 
  cv_df_long %&gt;% 
  dplyr::select(starts_with(&#39;rmse_&#39;)) %&gt;% 
  map(median) %&gt;% 
  unlist()

adjrsquared_long &lt;- c(pvalue_adjrsquared_long,auto_adjrsquared_long,
                       crit_adjrsquared_long, lasso_adjrsquared_long)
long_comparison &lt;- tibble(
  methods,
  RMSE_long, 
  adjrsquared_long
)
long_comparison %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">methods</th>
<th align="right">RMSE_long</th>
<th align="right">adjrsquared_long</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">pvalue</td>
<td align="right">0.0076781</td>
<td align="right">0.0125531</td>
</tr>
<tr class="even">
<td align="left">automatic</td>
<td align="right">0.0076892</td>
<td align="right">0.0117514</td>
</tr>
<tr class="odd">
<td align="left">criterion-based</td>
<td align="right">0.0076840</td>
<td align="right">0.0133905</td>
</tr>
<tr class="even">
<td align="left">LASSO</td>
<td align="right">0.0076838</td>
<td align="right">0.0131852</td>
</tr>
</tbody>
</table>
<pre class="r"><code># latitude: parsimony since the RMSE and Rsquared are similar
RMSE_lat &lt;- 
  cv_df_lat %&gt;% 
  dplyr::select(starts_with(&#39;rmse_&#39;)) %&gt;% 
  map(median) %&gt;% 
  unlist()

adjrsquared_lat &lt;- c(pvalue_adjrsquared_lat,auto_adjrsquared_lat,
                       crit_adjrsquared_lat, lasso_adjrsquared_lat)
lat_comparison &lt;- tibble(
  methods,
  RMSE_lat, 
  adjrsquared_lat
)
lat_comparison %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">methods</th>
<th align="right">RMSE_lat</th>
<th align="right">adjrsquared_lat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">pvalue</td>
<td align="right">0.0102359</td>
<td align="right">0.0130708</td>
</tr>
<tr class="even">
<td align="left">automatic</td>
<td align="right">0.0102351</td>
<td align="right">0.0144571</td>
</tr>
<tr class="odd">
<td align="left">criterion-based</td>
<td align="right">0.0102291</td>
<td align="right">0.0149498</td>
</tr>
<tr class="even">
<td align="left">LASSO</td>
<td align="right">0.0102291</td>
<td align="right">0.0149498</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="final-models" class="section level1">
<h1>Final Models</h1>
<div id="final-longitudinal-model" class="section level2">
<h2>Final Longitudinal Model</h2>
<p>The function of longitudinal has 5 predictors (shift + age + activity
+ reaction + sounds). Since the RMSE values and adjusted R-squared are
approximately same among all functions, the principal of parsimony tells
us to choose the the most succinct model. The formula of the latitudinal
function is: longitudinal = -73.97 + 0.0005639 shift - 0.0009412 age -
0.0002267 activity + 0.0004809 reaction + 0.002142 sounds.</p>
<pre class="r"><code># final model
long_model_final &lt;- 
  lm(long ~ shift + age + activity + reaction + sounds, data = sq_df)
print(long_model_final)</code></pre>
<pre><code>## 
## Call:
## lm(formula = long ~ shift + age + activity + reaction + sounds, 
##     data = sq_df)
## 
## Coefficients:
## (Intercept)        shift          age     activity     reaction       sounds  
##  -7.397e+01    5.639e-04   -9.412e-04   -2.267e-04    4.809e-04    2.142e-03</code></pre>
<pre class="r"><code>long_model_final %&gt;% broom::tidy()</code></pre>
<pre><code>## # A tibble: 6 × 5
##   term          estimate std.error  statistic   p.value
##   &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept) -74.0       0.000698 -105997.   0        
## 2 shift         0.000564  0.000282       2.00 0.0454   
## 3 age          -0.000941  0.000366      -2.57 0.0102   
## 4 activity     -0.000227  0.000103      -2.20 0.0279   
## 5 reaction      0.000481  0.000168       2.86 0.00424  
## 6 sounds        0.00214   0.000487       4.40 0.0000114</code></pre>
<p>The diagnosis plots of the final longitudinal prediction model:</p>
<pre class="r"><code>check_model(long_model_final, check = c(&quot;linearity&quot;, &quot;outliers&quot;, &quot;qq&quot;, &quot;normality&quot;))</code></pre>
<p><img src="function_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
</div>
<div id="final-latitudinal-model" class="section level2">
<h2>Final Latitudinal Model</h2>
<p>The function of latitudinal has 3 predictors (primary_fur_color +
reaction + sounds). Since the RMSE values and adjusted R-squared are
approximately same among all functions, the principal of parsimony tells
us to choose the the most succinct model. The formula of the latitudinal
function is: longitudinal = 40.7814005- 0.0013140 primary_fur_color +
0.0007784 reaction + 0.0029072 sounds.</p>
<pre class="r"><code>lat_model_final &lt;- 
  lm(lat ~ primary_fur_color + reaction + sounds, data = sq_df)
print(lat_model_final)</code></pre>
<pre><code>## 
## Call:
## lm(formula = lat ~ primary_fur_color + reaction + sounds, data = sq_df)
## 
## Coefficients:
##       (Intercept)  primary_fur_color           reaction             sounds  
##        40.7814005         -0.0013140          0.0007784          0.0029072</code></pre>
<pre class="r"><code>lat_model_final %&gt;% broom::tidy()</code></pre>
<pre><code>## # A tibble: 4 × 5
##   term               estimate std.error statistic    p.value
##   &lt;chr&gt;                 &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
## 1 (Intercept)       40.8       0.000521  78244.   0         
## 2 primary_fur_color -0.00131   0.000372     -3.54 0.000412  
## 3 reaction           0.000778  0.000223      3.48 0.000501  
## 4 sounds             0.00291   0.000648      4.49 0.00000751</code></pre>
<p>The diagnosis plots of the final latitudinal prediction model:</p>
<pre class="r"><code>check_model(lat_model_final, check = c(&quot;linearity&quot;, &quot;outliers&quot;, &quot;qq&quot;, &quot;normality&quot;))</code></pre>
<p><img src="function_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
