---
title: "model selcection"
output: github_document
date: "2022-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)
library(tidyverse)
library(readr)
library(dplyr)
library(ggplot2)
library(shiny)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	message = FALSE, 
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


```{r}
census =
  read_csv("2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv")%>% 
  janitor::clean_names() %>%
  #filter(!is.na(primary_fur_color))%>%
  mutate(date=as.character(date),
         long = as.numeric(x),
         lat = as.numeric(y),
         shift = as.character(shift),
         activity = case_when( running == "TRUE" ~ "running",
                               chasing == "TRUE" ~ "chasing",
                               climbing == "TRUE" ~ "climbing",
                               eating == "TRUE" ~ "eating",
                               foraging == "TRUE" ~ "foraging"),
         reaction = case_when( approaches == "TRUE" ~ "approaches",
                               indifferent == "TRUE" ~ "indifferent",
                               runs_from == "TRUE" ~ "runs_from"),
         sounds = case_when( kuks == "TRUE" ~ "kuks",
                               quaas == "TRUE" ~ "quaas",
                               moans == "TRUE" ~ "moans"))%>%
  select(-x,-y,-running,-chasing,-climbing,-eating,-foraging,-above_ground_sighter_measurement,-color_notes,-other_activities,-specific_location ,-tail_flags ,-tail_twitches,-other_interactions,-kuks,-quaas,-moans,-approaches,-indifferent,-runs_from)
```

# Data analysis

### Central Park Squirrel Data Collection Distribution

For our final project we were interested in looking at the NYC Squirrel Census collected by volunteers in October 2018. While the dataset is entitled “NYC Squirrel Census”, the data was geographically restricted to Central Park.

```{r}
dates <-census %>%
  mutate(Month= substr(date, 1,2), Day=substr(date, 3,4), Year=substr(date,5,9))

  dates %>% 
  group_by(Day, shift) %>%
  count() %>%
  ggplot() +
  geom_col(aes(x=Day, y=n, fill=shift)) +
  scale_fill_brewer(palette = "Paired") +
  labs(x = "Day", y ="Number of Observations", fill='Shift') +
  ggtitle('Central Park Squirrel Data Collection Distribution (Oct. 2018)') +
  theme(plot.title = element_text(hjust = 0.5)) 
```

```{r}
skimr::skim(census)
```


